### ISSUE TITLE
[Improvement] One underscore prefix to access the attributes (ex: a._keys)

### ISSUE THREAD

**Issue by rognoni** [sanand0/orderedattrdict#7]
For my project I need to uses the `values` keyword already used by `OrderedDict` so I was thinking if instead to use the classic way `["values"]`:

```
>>> a = AttrDict(keys=1)
>>> a.keys
<bound method AttrDict.keys of AttrDict([('keys', 1)])>
>>> a['keys']
1
```

we can use this convention:

```
>>> a._keys
1
```

**Comment by sanand0** [comment]
@rognoni -- is there any constraint around using `["values"]`? Before introducing a new convention, I'd just like to understand some of the factors driving this.

**Comment by rognoni** [comment]
@sanand0 No problem or constraint, I was only thinking if the code is more elegant for example replacing this:

``` python
    if params["values"].id:
        for row in entity.rows:
            if row.id == params["values"].id:
                id = params["values"].id
                _update_row(row, params)
                row.update(params["values"])
```

with this, if you do not see any contraindication (ex: reserved attributes with one underscore)

``` python
    if params._values.id:
        for row in entity.rows:
            if row.id == params._values.id:
                id = params._values.id
                _update_row(row, params)
                row.update(params._values)
```

Similarly to the JavaScript version of this code, I like to use the parenthesis-style only when I need to use the variables:

```
// javascript
app.schemas[params.schema].entities[params.entity].properties;

# python
js_schemas[params.schema].entities[params.entity].properties
```

**Comment by sanand0** [comment]
@rognoni, it took me a few days to collect my thoughts around this.

This would make it easier for the person writing code, but tougher for the person reading the code. When we use `params._values`, does it refer to `params['values']` or `params['_values']`? This is a question a maintainer of the project would find difficult to answer without knowing all default attributes of a dict.

Further, for `CounterAttrDict`, additional attributes like `elements` and `subtract` are excluded. Remembering that would be difficult. Specifically, 

```
>>> x = CounterAttrDict(subtract=10)
>>> x._subtract                # We need to use ._subtract here
>>> y = AtttrDict(subtract=10)
>>> y.subtract                 # ... but .subtract here
```

In the interest of making life simpler for maintainers, I'd rather use a less ambiguous and more explicit way.

There's an `__exclude_keys__` class attribute, One possibility is to use that and allow subclasses to determine which keys to allow. So you may be able to use `params.values` directly. Before we try this, would subclassing be an option for you?

**Comment by rognoni** [comment]
For the moment I'm working using this implementation:
https://github.com/rognoni/adaptable/blob/master/Backend/Python-Flask/util/json.py

but if I will have problems, I use your solution. The other difference comparing Python-JavaScript is this case:

``` python
# python: "has_key" is used to avoid KeyError exception
if property.default and not params._values.has_key(propertyName):

// javascript
if (property.default && params.values[propertyName] == null) {
```

**Comment by sanand0** [comment]
Closing this for now.
