### ISSUE TITLE
Add license file

### ISSUE THREAD

**Issue by bcbnz** [sanand0/orderedattrdict#8]
According to `setup.py` this project is under the MIT license. For many Linux distributions, packages with an MIT license require an explicit LICENSE file as the MIT license includes a unique copyright name (e.g., see the [Arch Wiki](https://wiki.archlinux.org/index.php/PKGBUILD#license) page on package licenses). Can you please add a LICENSE file to the repository so the project can be packaged?

**Comment by bcbnz** [comment]
Oh, and having done so, could you make a point release (e.g., 1.5.1) which includes the license? Cheers.

**Comment by sanand0** [comment]
@bcbnz -- this is done. Thanks for raising.
